version: v1alpha1
debug: false
persist: true
machine:
    type: worker
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.35.0
        extraArgs:
          rotate-server-certificates: "true"
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    install:
        disk: /dev/vda
        image: ghcr.io/siderolabs/installer:v1.12.2
        wipe: false
        grubUseUKICmdline: true
    features:
        rbac: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
cluster:
    clusterName: talos_truenas
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    # required by metric-server
    extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable
